FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD pccwg-test-init-topic.jar /opt/pccwg-test-init-topic/
EXPOSE 8080
WORKDIR /opt/pccwg-test-init-topic/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "pccwg-test-init-topic.jar"]
