services:
  zookeeper:
    container_name: zookeeper-test
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - pccwg-test-network      
  kafka:
    container_name: kafka-test
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - pccwg-test-network      
#  kafka-server:
#    container_name: pccwg-test-kafka
#    image: apache/kafka:3.8.0
#    ports:
#      - 9092:9092
#    networks:
#      - pccwg-test-network
  kafka-init:
    container_name: init-topic
    build: 
        context: pccwg-test-init-topic
        dockerfile: Dockerfile 
    depends_on:
      - kafka
    networks:
      - pccwg-test-network      
  api-server:
    container_name: pccwg-test-api
    build: 
        context: pccwg-test-api
        dockerfile: Dockerfile
    image: pccwg-test-api:latest
    ports:
      - 9090:9090
    networks:
      - pccwg-test-network
    depends_on:
      - kafka-init      
  kafka-consumer:
    container_name: kafka-consumer
    build: 
        context: pccwg-test-consumer
        dockerfile: Dockerfile 
    depends_on:
      - kafka
    networks:
      - pccwg-test-network
  web-ui:
    container_name: pccwg-test-web
    build: 
        context: pccwg-test-web
        dockerfile: Dockerfile
    image: pccwg-test-web:latest
    ports:
      - 8080:8080         
    depends_on:
      - api-server
    networks:
      - pccwg-test-network      
networks:
  pccwg-test-network:
    driver: bridge